apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-reader-deployment
spec:
  selector:
    matchLabels:
      app: assets
  template:
    metadata:
      labels:
        app: assets
    spec:
      containers:
      - name: framework-mongodb
        image: framework-mongodb:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"


