---
apiVersion: v1
kind: Service
metadata:
  name: infra-service
  labels:
    app: assets
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30002
  selector:
    app: assets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-deployment
spec:
  selector:
    matchLabels:
      app: assets
  template:
    metadata:
      labels:
        app: assets
    spec:
      containers:
      - name: backend-infra
        image: backend-infra:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

