---
apiVersion: v1
kind: Service
metadata:
  name: framework-restapi
  labels:
    app: assets
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
  selector:
    app: assets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets-deployment
spec:
  selector:
    matchLabels:
      app: assets
  template:
    metadata:
      labels:
        app: assets
    spec:
      containers:
      - name: assets-application
        image: sample:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
