---
apiVersion: v1
kind: Service
metadata:
  name: framework-restapi
  labels:
    app: assets
spec:
  ports:
  - port: 3000
  selector:
    app: assets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: framework-restapi
spec:
  selector:
    matchLabels:
      app: assets
  template:
    metadata:
      labels:
        app: assets
    spec:
      containers:
      - name: framework-restapi
        image: framework-restapi:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
