image: node:16.18

clone:
  depth: full

definitions:
  steps:
    - step: &agent
        name: Agent
        script:
          - export NX_BRANCH=$BITBUCKET_PR_ID

          - npm ci
          - npx nx-cloud start-agent

pipelines:
  pull-requests:
    '**':
      - parallel:
          - step:
              name: CI
              script:
                - export NX_BRANCH=$BITBUCKET_PR_ID

                - npm ci
                - npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
                - npx nx-cloud record -- yarn nx format:check
                - npx nx affected --target=lint & npx nx affected --target=test & npx nx affected --target=build
                - npx nx-cloud stop-all-agents
          - step: *agent
          - step: *agent
          - step: *agent
